#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

#include "log.h"

#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *entry = NULL;
	rt_entry_t *tmp = NULL;
	u32 tmp_mask = 0;
	list_for_each_entry(entry, &rtable, list) {
		u32 net = entry->dest & entry->mask;
		if(((dst & entry->mask) == net) && (entry->mask >= tmp_mask)){
			tmp = entry;
			tmp_mask = entry->mask;
		}
	}
	//fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	return tmp;
}


// forward the IP packet from the interface specified by longest_prefix_match, 
// when forwarding the packet, you should check the TTL, update the checksum,
// determine the next hop to forward the packet, then send the packet by 
// iface_send_packet_by_arp
void ip_forward_packet(u32 ip_dst, char *packet, int len)
{
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u8 ttl = ip->ttl;
	if(ttl <= 0) {
		// printf("ttl < 0, to icmp send \n");
		icmp_send_packet(packet,len,11,0);
	}
	else {
		ttl --;
		rt_entry_t *find_entry = longest_prefix_match(ntohl(ip->daddr));
		if(!find_entry) {
			// printf("find route fail, to icmp send\n");
			icmp_send_packet(packet,len,3,0);
			free(packet);
		}
		else {	//if find
			// printf("find entry\n");
			ip->ttl = ttl;
			ether_header_t *eth = (ether_header_t *)packet;
			eth->ether_type = htons(ETH_P_IP);
			memcpy(eth->ether_shost, find_entry->iface->mac, ETH_ALEN);
			ip->checksum = ip_checksum(ip);
			if(find_entry->gw == 0)
				iface_send_packet_by_arp(find_entry->iface, ip_dst, packet ,len);
			else
				iface_send_packet_by_arp(find_entry->iface, find_entry->gw, packet, len);
		}
	}
	//fprintf(stderr, "TODO: forward ip packet.\n");
}


// handle ip packet
//
// If the packet is ICMP echo request and the destination IP address is equal to
// the IP address of the iface, send ICMP echo reply; otherwise, forward the
// packet.
void handle_ip_packet(iface_info_t *iface, char *packet, int len)
{
	//printf("handle ip packet\n");
	struct iphdr *ip = packet_to_ip_hdr(packet);
	struct icmphdr *icmp = (struct icmphdr *) ((char *)ip + IP_BASE_HDR_SIZE);
	if(ip->protocol == 1 && icmp->type == 8){
		//printf("receive ping packet, to icmp send\n");
		icmp_send_packet(packet,len,0,0);
	}
	else {
		//printf("forward ip packet\n");
		ip_forward_packet(ntohl(ip->daddr), packet, len);
	}
	//fprintf(stderr, "TODO: handle ip packet: echo the ping packet, and forward other IP packets.\n");
}

// send IP packet
//
// Different from ip_forward_packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u32 dst = ntohl(ip->daddr);
	rt_entry_t *entry = longest_prefix_match(dst);
	if (!entry) {
		log(ERROR, "Could not find forwarding rule for IP (dst:"IP_FMT") packet.", 
				HOST_IP_FMT_STR(dst));
		free(packet);
		return ;
	}

	u32 next_hop = entry->gw;
	if (!next_hop)
		next_hop = dst;

	struct ether_header *eh = (struct ether_header *)packet;
	eh->ether_type = ntohs(ETH_P_IP);
	memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);

	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
}

